### ISSUE TITLE
breaks virtualenv

### ISSUE THREAD

**Issue by lukasz-virtualo** [urga/djangocms-slider#4]
##### Reproduction
1. Have a virtualenv with (some relevant) libs installed:
   
   ```
   Django==1.8.4
   django-cms==3.1.3
   ```
2. Install the slideshow:
   
   ``` bash
   pip install django-slideshow==0.1.5
   ```
##### Symptoms

Does not occur prior to (2) above. Running any comand with `manage.py`:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/djangocms_text_ckeditor/models.py", line 15, in <module>
    from cms.models import CMSPlugin
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/cms/models/__init__.py", line 3, in <module>
    from .pagemodel import *  # nopyflakes
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/cms/models/pagemodel.py", line 23, in <module>
    from cms.models.placeholdermodel import Placeholder
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/cms/models/placeholdermodel.py", line 13, in <module>
    from cms.utils.placeholder import PlaceholderNoAction, get_placeholder_conf
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/cms/utils/placeholder.py", line 23, in <module>
    from sekizai.helpers import get_varname, is_variable_extend_node
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/sekizai/helpers.py", line 3, in <module>
    from django.template import VariableNode, Variable
ImportError: cannot import name VariableNode
'''
```

**Comment by lukasz-virtualo** [comment]
Removing the lib from the virtualenv does not fix the problem, so damage is permanent.

**Comment by driesdesmet** [comment]
Can't reproduce (you had a typo in your last step: the package is called djangocms-slideshow, not django-slideshow. Could that be your issue?

These are the steps I did:

```
mkvirtualenv test
pip install Django==1.8.4
pip install django-cms==3.1.3
pip install djangocms-slideshow==0.1.5
```

Output: 
`Successfully installed django-admin-sortable-1.6.7 django-sekizai-0.7 djangocms-slideshow-0.1.5 easy-thumbnails-2.0.1 pillow-3.0.0`

**Comment by lukasz-virtualo** [comment]
There in fact is a typo in my previous post, as you pointed out:

``` bash
pip install djangocms-slideshow==0.1.5
```

is the proper invocation.
Have you tried to execute:

``` bash
python manage.py shell
```

after installing `djangocms-slideshow`?
Perhaps the problem affects other libraries than those listed. I include the complete contents of my venv:

``` dj-database-url==0.3.0
Django==1.8.4
django-bower==5.0.4
django-classy-tags==0.6.2
django-cms==3.1.3
django-filebrowser-no-grappelli==3.6.1
django-reversion==1.9.3
django-sekizai==0.8.2
Django-Select2==4.3.1
django-treebeard==3.0
djangocms-admin-style==0.2.8
djangocms-column==1.5
djangocms-file==0.1
djangocms-flash==0.2.0
djangocms-googlemap==0.3
djangocms-inherit==0.1
djangocms-installer==0.8.0
djangocms-link==1.7.1
djangocms-picture==0.1
djangocms-style==1.5
djangocms-teaser==0.1
djangocms-text-ckeditor==2.8.0
djangocms-video==0.1
html5lib==0.9999999
Pillow==2.9.0
pytz==2015.4
six==1.9.0
tzlocal==1.2
```

**Comment by driesdesmet** [comment]
I did try manage.py and didn't get an error. So you are right, it looks
like a dependancy problem. I know my plugin isn't thorougly tested,
especially the dependancies, and a lot has changed on django-cms. It was
developed against the 2.x series of django-cms. Sorry about that. You are
welcome to help improve it.

D.

Op zondag 29 november 2015 heeft lukasz-virtualo notifications@github.com
het volgende geschreven:

> There in fact is a typo in my previous post, as you pointed out:
> 
> pip install djangocms-slideshow==0.1.5
> 
> is the proper invocation.
> Have you tried to execute:
> 
> python manage.py shell
> 
> after installing djangocms-slideshow?
> Perhaps the problem affects other library than those listed. I include the
> complete contents of my venv:
> 
> Django==1.8.4
> django-bower==5.0.4
> django-classy-tags==0.6.2
> django-cms==3.1.3
> django-filebrowser-no-grappelli==3.6.1
> django-reversion==1.9.3
> django-sekizai==0.8.2
> Django-Select2==4.3.1
> django-treebeard==3.0
> djangocms-admin-style==0.2.8
> djangocms-column==1.5
> djangocms-file==0.1
> djangocms-flash==0.2.0
> djangocms-googlemap==0.3
> djangocms-inherit==0.1
> djangocms-installer==0.8.0
> djangocms-link==1.7.1
> djangocms-picture==0.1
> djangocms-style==1.5
> djangocms-teaser==0.1
> djangocms-text-ckeditor==2.8.0
> djangocms-video==0.1
> html5lib==0.9999999
> Pillow==2.9.0
> pytz==2015.4
> six==1.9.0
> tzlocal==1.2
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/urga/djangocms-slideshow/issues/4#issuecomment-160406594
> .

## 

Dries Desmet

_URGA | creatieve communicatie_

Zuiderlaan 69
8790 Waregem
t 056 61 41 94
m 0477 19 41 13
dries@urga.be
www.urga.be
